//! Embedded templates written to new projects by `statespace init`.

/// Instructions for coding agents on how to build and work with this app.
pub const AGENTS_MD: &str = include_str!("AGENTS.md");

/// Standard .gitignore for Statespace projects.
pub const GITIGNORE: &str = include_str!(".gitignore");

/// App API documentation served at the root of deployed apps.
pub const API_MD: &str = include_str!("API.md");

/// A bundled app starter (README.md + optional Dockerfile).
#[derive(Debug)]
pub struct Template {
    pub readme: &'static str,
    pub dockerfile: Option<&'static str>,
}

/// Curated starters shown in `statespace init --help`.
pub const CURATED_TEMPLATE_NAMES: &[&str] =
    &["mongodb", "mysql", "pgvector", "postgresql", "sqlite"];

/// Additional starters accepted by `statespace init --template` but hidden from help until curated.
pub const EXPERIMENTAL_TEMPLATE_NAMES: &[&str] = &[
    "clickhouse",
    "duckdb",
    "elasticsearch",
    "mssql",
    "qdrant",
    "redis",
    "snowflake",
    "vectorless-rag",
    "weaviate",
];

// Generated by build.rs from src/starters/.
// Provides `get(name: &str) -> Option<Template>` and `NAMES: &[&str]`.
include!(concat!(env!("OUT_DIR"), "/templates_generated.rs"));

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn all_named_starters_resolve() {
        for name in NAMES {
            assert!(
                get(name).is_some(),
                "Starter '{name}' listed in NAMES but not found"
            );
        }
    }

    #[test]
    fn unknown_starter_returns_none() {
        assert!(get("nonexistent").is_none());
    }

    #[test]
    fn hyphen_and_underscore_both_work() {
        // NAMES uses hyphens as the canonical display form; get() normalizes '-' → '_'.
        let name = NAMES
            .iter()
            .find(|n| n.contains('-'))
            .expect("at least one starter should have a hyphen in its name");
        let underscored = name.replace('-', "_");
        assert!(get(name).is_some(), "{name} should resolve via hyphen");
        assert!(
            get(&underscored).is_some(),
            "{underscored} should resolve via underscore"
        );
    }

    #[test]
    fn curated_and_experimental_lists_cover_all_starters() {
        let curated: BTreeSet<_> = CURATED_TEMPLATE_NAMES.iter().copied().collect();
        let experimental: BTreeSet<_> = EXPERIMENTAL_TEMPLATE_NAMES.iter().copied().collect();
        let all: BTreeSet<_> = NAMES.iter().copied().collect();

        assert!(
            curated.is_disjoint(&experimental),
            "curated and experimental template lists must not overlap"
        );

        let combined: BTreeSet<_> = curated.union(&experimental).copied().collect();
        assert_eq!(combined, all, "every starter should be classified");
    }
}
