//! Embedded templates written to new projects by `statespace init`.

/// Default README written to new projects by `statespace init`.
pub const README_MD: &str = include_str!("README.md");

/// Instructions for coding agents on how to build and work with this app.
pub const AGENTS_MD: &str = include_str!("AGENTS.md");

/// Standard .gitignore for Statespace projects.
pub const GITIGNORE: &str = include_str!(".gitignore");

/// App API documentation served at the root of deployed apps.
pub const LLMS_TXT: &str = include_str!("llms.txt");

/// A bundled app starter (README.md + optional Dockerfile).
#[derive(Debug)]
pub struct Template {
    pub readme: &'static str,
    pub dockerfile: Option<&'static str>,
}

// Generated by build.rs from src/starters/.
// Provides `get(name: &str) -> Option<Template>` and `NAMES: &[&str]`.
include!(concat!(env!("OUT_DIR"), "/templates_generated.rs"));

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn all_named_starters_resolve() {
        for name in NAMES {
            assert!(
                get(name).is_some(),
                "Starter '{name}' listed in NAMES but not found"
            );
        }
    }

    #[test]
    fn unknown_starter_returns_none() {
        assert!(get("nonexistent").is_none());
    }

    #[test]
    fn hyphen_and_underscore_both_work() {
        // NAMES uses hyphens as the canonical display form; get() normalizes '-' → '_'.
        let name = NAMES
            .iter()
            .find(|n| n.contains('-'))
            .expect("at least one starter should have a hyphen in its name");
        let underscored = name.replace('-', "_");
        assert!(get(name).is_some(), "{name} should resolve via hyphen");
        assert!(
            get(&underscored).is_some(),
            "{underscored} should resolve via underscore"
        );
    }
}
