/// A bundled app template (README.md + optional Dockerfile).
#[derive(Debug)]
pub struct Template {
    pub readme: &'static str,
    pub dockerfile: Option<&'static str>,
}

// Generated by build.rs from crates/statespace-templates/src/init/.
// Provides `get(name: &str) -> Option<Template>` and `NAMES: &[&str]`.
include!(concat!(env!("OUT_DIR"), "/templates_generated.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_named_templates_resolve() {
        for name in NAMES {
            assert!(get(name).is_some(), "Template '{name}' listed in NAMES but not found");
        }
    }

    #[test]
    fn unknown_template_returns_none() {
        assert!(get("nonexistent").is_none());
    }

    #[test]
    fn hyphen_and_underscore_both_work() {
        assert!(get("vectorless-rag").is_some());
        assert!(get("vectorless_rag").is_some());
    }
}
